#
#
# --- CLIMATE ---------------------------------------------------------
#
# scaling for atmospheric CO2 radiative forcing, relative to 278 ppm
ea_radfor_scl_co2=12.0
#
# --- BIOLOGICAL NEW PRODUCTION ---------------------------------------
#
# No biology
bg_par_bio_prodopt='NONE'
#
# --- DATA SAVING -----------------------------------------------------
#
bg_par_data_save_level=10
bg_ctrl_debug_lvl0=.true.
ma_debug_loop=1
#
# --- FORCINGS --------------------------------------------------------
#
# add a geothermal heat flux (W m-2)
bg_ctrl_force_GOLDSTEInTS=.TRUE.
bg_par_Fgeothermal=100.0E-3
#
# --- MISC ------------------------------------------------------------
#
#
# --- END -------------------------------------------------------------
#
#