FPPOPTS='$(DEFINE)GENIENX=36 $(DEFINE)GENIENY=36 $(DEFINE)GENIENL=1 $(DEFINE)GOLDSTEINNLONS=36 $(DEFINE)GOLDSTEINNLATS=36 $(DEFINE)GOLDSTEINNLEVS=16 $(DEFINE)GOLDSTEINNTRACS=16 '
MODULE_NAMES='embm goldstein goldsteinseaice biogem atchem '
FPPOPTS2='$(DEFINE)USE_embm $(DEFINE)USE_goldstein $(DEFINE)USE_goldsteinseaice $(DEFINE)USE_biogem $(DEFINE)USE_atchem '
