OUTROOT=/home/portabello/cgenie_output
CODEDIR=/home/portabello/cgenie.muffin
RUNTIME_ROOT=../../cgenie.muffin
RUNTIME_OUTDIR=.
EXPID=190210_GMD_e6PALO2_10uMSO4_Hesc_SPIN
FIXEDATMOSFILE=data_fixedatmos
GLIMMERFILE=data_glimmer.config
igcm_module=genie-igcm
BFGROOT=EMPTY
MODULE_NAMES='embm goldstein goldsteinseaice biogem atchem '