#
#
# --- CLIMATE ---------------------------------------------------------
#
# scaling for atmospheric CO2 radiative forcing, relative to 278 ppm
ea_radfor_scl_co2=1.0
#
# --- BIOLOGICAL NEW PRODUCTION ---------------------------------------
#
# No biology
bg_par_bio_prodopt='NONE'
#
# --- DATA SAVING -----------------------------------------------------
#
# date saving & reporting options
bg_par_data_save_level=6
bg_ctrl_debug_lvl0=.true.
ma_debug_loop=2
#
# --- END -------------------------------------------------------------
#
#
